// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: avg_price.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvgPriceByParityExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parity        uint64                 `protobuf:"varint,1,opt,name=Parity,proto3" json:"Parity,omitempty"`
	Exchange      uint64                 `protobuf:"varint,2,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvgPriceByParityExchangeRequest) Reset() {
	*x = GetAvgPriceByParityExchangeRequest{}
	mi := &file_avg_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvgPriceByParityExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgPriceByParityExchangeRequest) ProtoMessage() {}

func (x *GetAvgPriceByParityExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgPriceByParityExchangeRequest.ProtoReflect.Descriptor instead.
func (*GetAvgPriceByParityExchangeRequest) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvgPriceByParityExchangeRequest) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeRequest) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

type GetAvgPriceByParityExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvgPriceByParityExchangeResponse) Reset() {
	*x = GetAvgPriceByParityExchangeResponse{}
	mi := &file_avg_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvgPriceByParityExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgPriceByParityExchangeResponse) ProtoMessage() {}

func (x *GetAvgPriceByParityExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgPriceByParityExchangeResponse.ProtoReflect.Descriptor instead.
func (*GetAvgPriceByParityExchangeResponse) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{1}
}

type CreateAveragePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=From,proto3" json:"From,omitempty"`
	To            uint64                 `protobuf:"varint,2,opt,name=To,proto3" json:"To,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAveragePriceRequest) Reset() {
	*x = CreateAveragePriceRequest{}
	mi := &file_avg_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAveragePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAveragePriceRequest) ProtoMessage() {}

func (x *CreateAveragePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAveragePriceRequest.ProtoReflect.Descriptor instead.
func (*CreateAveragePriceRequest) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAveragePriceRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *CreateAveragePriceRequest) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

type CreateAveragePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAveragePriceResponse) Reset() {
	*x = CreateAveragePriceResponse{}
	mi := &file_avg_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAveragePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAveragePriceResponse) ProtoMessage() {}

func (x *CreateAveragePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAveragePriceResponse.ProtoReflect.Descriptor instead.
func (*CreateAveragePriceResponse) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{3}
}

var File_avg_price_proto protoreflect.FileDescriptor

var file_avg_price_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x61, 0x76, 0x67, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x58, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x42, 0x79, 0x50, 0x61, 0x72, 0x69, 0x74, 0x79, 0x45, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x50, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22,
	0x25, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x42, 0x79,
	0x50, 0x61, 0x72, 0x69, 0x74, 0x79, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x54, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_avg_price_proto_rawDescOnce sync.Once
	file_avg_price_proto_rawDescData []byte
)

func file_avg_price_proto_rawDescGZIP() []byte {
	file_avg_price_proto_rawDescOnce.Do(func() {
		file_avg_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avg_price_proto_rawDesc), len(file_avg_price_proto_rawDesc)))
	})
	return file_avg_price_proto_rawDescData
}

var file_avg_price_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_avg_price_proto_goTypes = []any{
	(*GetAvgPriceByParityExchangeRequest)(nil),  // 0: pb.GetAvgPriceByParityExchangeRequest
	(*GetAvgPriceByParityExchangeResponse)(nil), // 1: pb.GetAvgPriceByParityExchangeResponse
	(*CreateAveragePriceRequest)(nil),           // 2: pb.CreateAveragePriceRequest
	(*CreateAveragePriceResponse)(nil),          // 3: pb.CreateAveragePriceResponse
}
var file_avg_price_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avg_price_proto_init() }
func file_avg_price_proto_init() {
	if File_avg_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avg_price_proto_rawDesc), len(file_avg_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avg_price_proto_goTypes,
		DependencyIndexes: file_avg_price_proto_depIdxs,
		MessageInfos:      file_avg_price_proto_msgTypes,
	}.Build()
	File_avg_price_proto = out.File
	file_avg_price_proto_goTypes = nil
	file_avg_price_proto_depIdxs = nil
}
