// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: avg_price.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvgPriceByParityExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parity        uint64                 `protobuf:"varint,1,opt,name=Parity,proto3" json:"Parity,omitempty"`
	Exchange      uint64                 `protobuf:"varint,2,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvgPriceByParityExchangeRequest) Reset() {
	*x = GetAvgPriceByParityExchangeRequest{}
	mi := &file_avg_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvgPriceByParityExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgPriceByParityExchangeRequest) ProtoMessage() {}

func (x *GetAvgPriceByParityExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgPriceByParityExchangeRequest.ProtoReflect.Descriptor instead.
func (*GetAvgPriceByParityExchangeRequest) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvgPriceByParityExchangeRequest) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeRequest) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

type GetAvgPriceByParityExchangeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Parity               uint64                 `protobuf:"varint,1,opt,name=Parity,proto3" json:"Parity,omitempty"`
	Exchange             uint64                 `protobuf:"varint,2,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Day                  float64                `protobuf:"fixed64,3,opt,name=Day,proto3" json:"Day,omitempty"`
	DayRoc               float64                `protobuf:"fixed64,4,opt,name=DayRoc,proto3" json:"DayRoc,omitempty"`
	DayUpdateTimestamp   uint64                 `protobuf:"varint,5,opt,name=DayUpdateTimestamp,proto3" json:"DayUpdateTimestamp,omitempty"`
	Week                 float64                `protobuf:"fixed64,6,opt,name=Week,proto3" json:"Week,omitempty"`
	WeekRoc              float64                `protobuf:"fixed64,7,opt,name=WeekRoc,proto3" json:"WeekRoc,omitempty"`
	WeekUpdateTimestamp  uint64                 `protobuf:"varint,8,opt,name=WeekUpdateTimestamp,proto3" json:"WeekUpdateTimestamp,omitempty"`
	Month                float64                `protobuf:"fixed64,9,opt,name=Month,proto3" json:"Month,omitempty"`
	MonthRoc             float64                `protobuf:"fixed64,10,opt,name=MonthRoc,proto3" json:"MonthRoc,omitempty"`
	MonthUpdateTimestamp uint64                 `protobuf:"varint,11,opt,name=MonthUpdateTimestamp,proto3" json:"MonthUpdateTimestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAvgPriceByParityExchangeResponse) Reset() {
	*x = GetAvgPriceByParityExchangeResponse{}
	mi := &file_avg_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvgPriceByParityExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgPriceByParityExchangeResponse) ProtoMessage() {}

func (x *GetAvgPriceByParityExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgPriceByParityExchangeResponse.ProtoReflect.Descriptor instead.
func (*GetAvgPriceByParityExchangeResponse) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{1}
}

func (x *GetAvgPriceByParityExchangeResponse) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetDay() float64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetDayRoc() float64 {
	if x != nil {
		return x.DayRoc
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetDayUpdateTimestamp() uint64 {
	if x != nil {
		return x.DayUpdateTimestamp
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetWeek() float64 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetWeekRoc() float64 {
	if x != nil {
		return x.WeekRoc
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetWeekUpdateTimestamp() uint64 {
	if x != nil {
		return x.WeekUpdateTimestamp
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetMonth() float64 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetMonthRoc() float64 {
	if x != nil {
		return x.MonthRoc
	}
	return 0
}

func (x *GetAvgPriceByParityExchangeResponse) GetMonthUpdateTimestamp() uint64 {
	if x != nil {
		return x.MonthUpdateTimestamp
	}
	return 0
}

type UpdateAveragePriceRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Parity               uint64                 `protobuf:"varint,1,opt,name=Parity,proto3" json:"Parity,omitempty"`
	Exchange             uint64                 `protobuf:"varint,2,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Day                  float64                `protobuf:"fixed64,3,opt,name=Day,proto3" json:"Day,omitempty"`
	DayRoc               float64                `protobuf:"fixed64,4,opt,name=DayRoc,proto3" json:"DayRoc,omitempty"`
	DayUpdateTimestamp   uint64                 `protobuf:"varint,5,opt,name=DayUpdateTimestamp,proto3" json:"DayUpdateTimestamp,omitempty"`
	Week                 float64                `protobuf:"fixed64,6,opt,name=Week,proto3" json:"Week,omitempty"`
	WeekRoc              float64                `protobuf:"fixed64,7,opt,name=WeekRoc,proto3" json:"WeekRoc,omitempty"`
	WeekUpdateTimestamp  uint64                 `protobuf:"varint,8,opt,name=WeekUpdateTimestamp,proto3" json:"WeekUpdateTimestamp,omitempty"`
	Month                float64                `protobuf:"fixed64,9,opt,name=Month,proto3" json:"Month,omitempty"`
	MonthRoc             float64                `protobuf:"fixed64,10,opt,name=MonthRoc,proto3" json:"MonthRoc,omitempty"`
	MonthUpdateTimestamp uint64                 `protobuf:"varint,11,opt,name=MonthUpdateTimestamp,proto3" json:"MonthUpdateTimestamp,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateAveragePriceRequest) Reset() {
	*x = UpdateAveragePriceRequest{}
	mi := &file_avg_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAveragePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAveragePriceRequest) ProtoMessage() {}

func (x *UpdateAveragePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAveragePriceRequest.ProtoReflect.Descriptor instead.
func (*UpdateAveragePriceRequest) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAveragePriceRequest) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetDay() float64 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetDayRoc() float64 {
	if x != nil {
		return x.DayRoc
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetDayUpdateTimestamp() uint64 {
	if x != nil {
		return x.DayUpdateTimestamp
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetWeek() float64 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetWeekRoc() float64 {
	if x != nil {
		return x.WeekRoc
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetWeekUpdateTimestamp() uint64 {
	if x != nil {
		return x.WeekUpdateTimestamp
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetMonth() float64 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetMonthRoc() float64 {
	if x != nil {
		return x.MonthRoc
	}
	return 0
}

func (x *UpdateAveragePriceRequest) GetMonthUpdateTimestamp() uint64 {
	if x != nil {
		return x.MonthUpdateTimestamp
	}
	return 0
}

type UpdateAveragePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAveragePriceResponse) Reset() {
	*x = UpdateAveragePriceResponse{}
	mi := &file_avg_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAveragePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAveragePriceResponse) ProtoMessage() {}

func (x *UpdateAveragePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avg_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAveragePriceResponse.ProtoReflect.Descriptor instead.
func (*UpdateAveragePriceResponse) Descriptor() ([]byte, []int) {
	return file_avg_price_proto_rawDescGZIP(), []int{3}
}

var File_avg_price_proto protoreflect.FileDescriptor

const file_avg_price_proto_rawDesc = "" +
	"\n" +
	"\x0favg_price.proto\x12\x02pb\"X\n" +
	"\"GetAvgPriceByParityExchangeRequest\x12\x16\n" +
	"\x06Parity\x18\x01 \x01(\x04R\x06Parity\x12\x1a\n" +
	"\bExchange\x18\x02 \x01(\x04R\bExchange\"\xf9\x02\n" +
	"#GetAvgPriceByParityExchangeResponse\x12\x16\n" +
	"\x06Parity\x18\x01 \x01(\x04R\x06Parity\x12\x1a\n" +
	"\bExchange\x18\x02 \x01(\x04R\bExchange\x12\x10\n" +
	"\x03Day\x18\x03 \x01(\x01R\x03Day\x12\x16\n" +
	"\x06DayRoc\x18\x04 \x01(\x01R\x06DayRoc\x12.\n" +
	"\x12DayUpdateTimestamp\x18\x05 \x01(\x04R\x12DayUpdateTimestamp\x12\x12\n" +
	"\x04Week\x18\x06 \x01(\x01R\x04Week\x12\x18\n" +
	"\aWeekRoc\x18\a \x01(\x01R\aWeekRoc\x120\n" +
	"\x13WeekUpdateTimestamp\x18\b \x01(\x04R\x13WeekUpdateTimestamp\x12\x14\n" +
	"\x05Month\x18\t \x01(\x01R\x05Month\x12\x1a\n" +
	"\bMonthRoc\x18\n" +
	" \x01(\x01R\bMonthRoc\x122\n" +
	"\x14MonthUpdateTimestamp\x18\v \x01(\x04R\x14MonthUpdateTimestamp\"\xef\x02\n" +
	"\x19UpdateAveragePriceRequest\x12\x16\n" +
	"\x06Parity\x18\x01 \x01(\x04R\x06Parity\x12\x1a\n" +
	"\bExchange\x18\x02 \x01(\x04R\bExchange\x12\x10\n" +
	"\x03Day\x18\x03 \x01(\x01R\x03Day\x12\x16\n" +
	"\x06DayRoc\x18\x04 \x01(\x01R\x06DayRoc\x12.\n" +
	"\x12DayUpdateTimestamp\x18\x05 \x01(\x04R\x12DayUpdateTimestamp\x12\x12\n" +
	"\x04Week\x18\x06 \x01(\x01R\x04Week\x12\x18\n" +
	"\aWeekRoc\x18\a \x01(\x01R\aWeekRoc\x120\n" +
	"\x13WeekUpdateTimestamp\x18\b \x01(\x04R\x13WeekUpdateTimestamp\x12\x14\n" +
	"\x05Month\x18\t \x01(\x01R\x05Month\x12\x1a\n" +
	"\bMonthRoc\x18\n" +
	" \x01(\x01R\bMonthRoc\x122\n" +
	"\x14MonthUpdateTimestamp\x18\v \x01(\x04R\x14MonthUpdateTimestamp\"\x1c\n" +
	"\x1aUpdateAveragePriceResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_avg_price_proto_rawDescOnce sync.Once
	file_avg_price_proto_rawDescData []byte
)

func file_avg_price_proto_rawDescGZIP() []byte {
	file_avg_price_proto_rawDescOnce.Do(func() {
		file_avg_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avg_price_proto_rawDesc), len(file_avg_price_proto_rawDesc)))
	})
	return file_avg_price_proto_rawDescData
}

var file_avg_price_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_avg_price_proto_goTypes = []any{
	(*GetAvgPriceByParityExchangeRequest)(nil),  // 0: pb.GetAvgPriceByParityExchangeRequest
	(*GetAvgPriceByParityExchangeResponse)(nil), // 1: pb.GetAvgPriceByParityExchangeResponse
	(*UpdateAveragePriceRequest)(nil),           // 2: pb.UpdateAveragePriceRequest
	(*UpdateAveragePriceResponse)(nil),          // 3: pb.UpdateAveragePriceResponse
}
var file_avg_price_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avg_price_proto_init() }
func file_avg_price_proto_init() {
	if File_avg_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avg_price_proto_rawDesc), len(file_avg_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avg_price_proto_goTypes,
		DependencyIndexes: file_avg_price_proto_depIdxs,
		MessageInfos:      file_avg_price_proto_msgTypes,
	}.Build()
	File_avg_price_proto = out.File
	file_avg_price_proto_goTypes = nil
	file_avg_price_proto_depIdxs = nil
}
