// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: exchange.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeService_ListExchange_FullMethodName      = "/pb.ExchangeService/ListExchange"
	ExchangeService_ListTradeConfig_FullMethodName   = "/pb.ExchangeService/ListTradeConfig"
	ExchangeService_CreateTradeConfig_FullMethodName = "/pb.ExchangeService/CreateTradeConfig"
)

// ExchangeServiceClient is the client API for ExchangeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeServiceClient interface {
	ListExchange(ctx context.Context, in *ListExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
	ListTradeConfig(ctx context.Context, in *ListTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error)
	CreateTradeConfig(ctx context.Context, in *CreateTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error)
}

type exchangeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeServiceClient(cc grpc.ClientConnInterface) ExchangeServiceClient {
	return &exchangeServiceClient{cc}
}

func (c *exchangeServiceClient) ListExchange(ctx context.Context, in *ListExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, ExchangeService_ListExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) ListTradeConfig(ctx context.Context, in *ListTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeConfigResponse)
	err := c.cc.Invoke(ctx, ExchangeService_ListTradeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeServiceClient) CreateTradeConfig(ctx context.Context, in *CreateTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeConfigResponse)
	err := c.cc.Invoke(ctx, ExchangeService_CreateTradeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeServiceServer is the server API for ExchangeService service.
// All implementations must embed UnimplementedExchangeServiceServer
// for forward compatibility.
type ExchangeServiceServer interface {
	ListExchange(context.Context, *ListExchangeRequest) (*ExchangeResponse, error)
	ListTradeConfig(context.Context, *ListTradeConfigRequest) (*TradeConfigResponse, error)
	CreateTradeConfig(context.Context, *CreateTradeConfigRequest) (*TradeConfigResponse, error)
	mustEmbedUnimplementedExchangeServiceServer()
}

// UnimplementedExchangeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeServiceServer struct{}

func (UnimplementedExchangeServiceServer) ListExchange(context.Context, *ListExchangeRequest) (*ExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExchange not implemented")
}
func (UnimplementedExchangeServiceServer) ListTradeConfig(context.Context, *ListTradeConfigRequest) (*TradeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTradeConfig not implemented")
}
func (UnimplementedExchangeServiceServer) CreateTradeConfig(context.Context, *CreateTradeConfigRequest) (*TradeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTradeConfig not implemented")
}
func (UnimplementedExchangeServiceServer) mustEmbedUnimplementedExchangeServiceServer() {}
func (UnimplementedExchangeServiceServer) testEmbeddedByValue()                         {}

// UnsafeExchangeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeServiceServer will
// result in compilation errors.
type UnsafeExchangeServiceServer interface {
	mustEmbedUnimplementedExchangeServiceServer()
}

func RegisterExchangeServiceServer(s grpc.ServiceRegistrar, srv ExchangeServiceServer) {
	// If the following call pancis, it indicates UnimplementedExchangeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeService_ServiceDesc, srv)
}

func _ExchangeService_ListExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).ListExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeService_ListExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).ListExchange(ctx, req.(*ListExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_ListTradeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).ListTradeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeService_ListTradeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).ListTradeConfig(ctx, req.(*ListTradeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeService_CreateTradeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServiceServer).CreateTradeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeService_CreateTradeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServiceServer).CreateTradeConfig(ctx, req.(*CreateTradeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeService_ServiceDesc is the grpc.ServiceDesc for ExchangeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ExchangeService",
	HandlerType: (*ExchangeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExchange",
			Handler:    _ExchangeService_ListExchange_Handler,
		},
		{
			MethodName: "ListTradeConfig",
			Handler:    _ExchangeService_ListTradeConfig_Handler,
		},
		{
			MethodName: "CreateTradeConfig",
			Handler:    _ExchangeService_CreateTradeConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exchange.proto",
}
