// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: operation_history.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationHistory struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory        uint64                 `protobuf:"varint,1,opt,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	Operation               uint64                 `protobuf:"varint,2,opt,name=Operation,proto3" json:"Operation,omitempty"`
	TransactionType         uint64                 `protobuf:"varint,3,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	CoinPrice               float64                `protobuf:"fixed64,4,opt,name=CoinPrice,proto3" json:"CoinPrice,omitempty"`
	CoinQuantity            float64                `protobuf:"fixed64,5,opt,name=CoinQuantity,proto3" json:"CoinQuantity,omitempty"`
	StablePrice             float64                `protobuf:"fixed64,6,opt,name=StablePrice,proto3" json:"StablePrice,omitempty"`
	StableQuantity          float64                `protobuf:"fixed64,7,opt,name=StableQuantity,proto3" json:"StableQuantity,omitempty"`
	OperationExchangeId     string                 `protobuf:"bytes,8,opt,name=OperationExchangeId,proto3" json:"OperationExchangeId,omitempty"`
	OperationExchangeStatus uint64                 `protobuf:"varint,9,opt,name=OperationExchangeStatus,proto3" json:"OperationExchangeStatus,omitempty"`
	Fee                     float64                `protobuf:"fixed64,10,opt,name=Fee,proto3" json:"Fee,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OperationHistory) Reset() {
	*x = OperationHistory{}
	mi := &file_operation_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationHistory) ProtoMessage() {}

func (x *OperationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationHistory.ProtoReflect.Descriptor instead.
func (*OperationHistory) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{0}
}

func (x *OperationHistory) GetOperationHistory() uint64 {
	if x != nil {
		return x.OperationHistory
	}
	return 0
}

func (x *OperationHistory) GetOperation() uint64 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *OperationHistory) GetTransactionType() uint64 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

func (x *OperationHistory) GetCoinPrice() float64 {
	if x != nil {
		return x.CoinPrice
	}
	return 0
}

func (x *OperationHistory) GetCoinQuantity() float64 {
	if x != nil {
		return x.CoinQuantity
	}
	return 0
}

func (x *OperationHistory) GetStablePrice() float64 {
	if x != nil {
		return x.StablePrice
	}
	return 0
}

func (x *OperationHistory) GetStableQuantity() float64 {
	if x != nil {
		return x.StableQuantity
	}
	return 0
}

func (x *OperationHistory) GetOperationExchangeId() string {
	if x != nil {
		return x.OperationExchangeId
	}
	return ""
}

func (x *OperationHistory) GetOperationExchangeStatus() uint64 {
	if x != nil {
		return x.OperationExchangeStatus
	}
	return 0
}

func (x *OperationHistory) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type GetOperationHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	OrderIdLink   uint64                 `protobuf:"varint,2,opt,name=OrderIdLink,proto3" json:"OrderIdLink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationHistoryRequest) Reset() {
	*x = GetOperationHistoryRequest{}
	mi := &file_operation_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationHistoryRequest) ProtoMessage() {}

func (x *GetOperationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetOperationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetOperationHistoryRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOperationHistoryRequest) GetOrderIdLink() uint64 {
	if x != nil {
		return x.OrderIdLink
	}
	return 0
}

type GetOperationHistoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory *OperationHistory      `protobuf:"bytes,1,opt,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetOperationHistoryResponse) Reset() {
	*x = GetOperationHistoryResponse{}
	mi := &file_operation_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationHistoryResponse) ProtoMessage() {}

func (x *GetOperationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetOperationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationHistoryResponse) GetOperationHistory() *OperationHistory {
	if x != nil {
		return x.OperationHistory
	}
	return nil
}

type ListOperationHistoryByOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     uint64                 `protobuf:"varint,1,opt,name=Operation,proto3" json:"Operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationHistoryByOperationRequest) Reset() {
	*x = ListOperationHistoryByOperationRequest{}
	mi := &file_operation_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationHistoryByOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationHistoryByOperationRequest) ProtoMessage() {}

func (x *ListOperationHistoryByOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationHistoryByOperationRequest.ProtoReflect.Descriptor instead.
func (*ListOperationHistoryByOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{3}
}

func (x *ListOperationHistoryByOperationRequest) GetOperation() uint64 {
	if x != nil {
		return x.Operation
	}
	return 0
}

type ListOperationHistoryByOperationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory []*OperationHistory    `protobuf:"bytes,1,rep,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListOperationHistoryByOperationResponse) Reset() {
	*x = ListOperationHistoryByOperationResponse{}
	mi := &file_operation_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationHistoryByOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationHistoryByOperationResponse) ProtoMessage() {}

func (x *ListOperationHistoryByOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationHistoryByOperationResponse.ProtoReflect.Descriptor instead.
func (*ListOperationHistoryByOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{4}
}

func (x *ListOperationHistoryByOperationResponse) GetOperationHistory() []*OperationHistory {
	if x != nil {
		return x.OperationHistory
	}
	return nil
}

type GetLastBuyRegisterByOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     uint64                 `protobuf:"varint,1,opt,name=Operation,proto3" json:"Operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastBuyRegisterByOperationRequest) Reset() {
	*x = GetLastBuyRegisterByOperationRequest{}
	mi := &file_operation_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastBuyRegisterByOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastBuyRegisterByOperationRequest) ProtoMessage() {}

func (x *GetLastBuyRegisterByOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastBuyRegisterByOperationRequest.ProtoReflect.Descriptor instead.
func (*GetLastBuyRegisterByOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{5}
}

func (x *GetLastBuyRegisterByOperationRequest) GetOperation() uint64 {
	if x != nil {
		return x.Operation
	}
	return 0
}

type GetLastBuyRegisterByOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinQuantity  float64                `protobuf:"fixed64,1,opt,name=CoinQuantity,proto3" json:"CoinQuantity,omitempty"`
	Fee           float64                `protobuf:"fixed64,2,opt,name=Fee,proto3" json:"Fee,omitempty"`
	Status        uint64                 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastBuyRegisterByOperationResponse) Reset() {
	*x = GetLastBuyRegisterByOperationResponse{}
	mi := &file_operation_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastBuyRegisterByOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastBuyRegisterByOperationResponse) ProtoMessage() {}

func (x *GetLastBuyRegisterByOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastBuyRegisterByOperationResponse.ProtoReflect.Descriptor instead.
func (*GetLastBuyRegisterByOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{6}
}

func (x *GetLastBuyRegisterByOperationResponse) GetCoinQuantity() float64 {
	if x != nil {
		return x.CoinQuantity
	}
	return 0
}

func (x *GetLastBuyRegisterByOperationResponse) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *GetLastBuyRegisterByOperationResponse) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateOperationHistoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory *OperationHistory      `protobuf:"bytes,1,opt,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOperationHistoryRequest) Reset() {
	*x = CreateOperationHistoryRequest{}
	mi := &file_operation_history_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationHistoryRequest) ProtoMessage() {}

func (x *CreateOperationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationHistoryRequest.ProtoReflect.Descriptor instead.
func (*CreateOperationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{7}
}

func (x *CreateOperationHistoryRequest) GetOperationHistory() *OperationHistory {
	if x != nil {
		return x.OperationHistory
	}
	return nil
}

type CreateOperationHistoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory *OperationHistory      `protobuf:"bytes,1,opt,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOperationHistoryResponse) Reset() {
	*x = CreateOperationHistoryResponse{}
	mi := &file_operation_history_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationHistoryResponse) ProtoMessage() {}

func (x *CreateOperationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationHistoryResponse.ProtoReflect.Descriptor instead.
func (*CreateOperationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOperationHistoryResponse) GetOperationHistory() *OperationHistory {
	if x != nil {
		return x.OperationHistory
	}
	return nil
}

type UpdateOperationHistoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory *OperationHistory      `protobuf:"bytes,1,opt,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateOperationHistoryRequest) Reset() {
	*x = UpdateOperationHistoryRequest{}
	mi := &file_operation_history_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperationHistoryRequest) ProtoMessage() {}

func (x *UpdateOperationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperationHistoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateOperationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOperationHistoryRequest) GetOperationHistory() *OperationHistory {
	if x != nil {
		return x.OperationHistory
	}
	return nil
}

type UpdateOperationHistoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OperationHistory *OperationHistory      `protobuf:"bytes,1,opt,name=OperationHistory,proto3" json:"OperationHistory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateOperationHistoryResponse) Reset() {
	*x = UpdateOperationHistoryResponse{}
	mi := &file_operation_history_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperationHistoryResponse) ProtoMessage() {}

func (x *UpdateOperationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperationHistoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateOperationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOperationHistoryResponse) GetOperationHistory() *OperationHistory {
	if x != nil {
		return x.OperationHistory
	}
	return nil
}

var File_operation_history_proto protoreflect.FileDescriptor

const file_operation_history_proto_rawDesc = "" +
	"\n" +
	"\x17operation_history.proto\x12\x02pb\"\x90\x03\n" +
	"\x10OperationHistory\x12*\n" +
	"\x10OperationHistory\x18\x01 \x01(\x04R\x10OperationHistory\x12\x1c\n" +
	"\tOperation\x18\x02 \x01(\x04R\tOperation\x12(\n" +
	"\x0fTransactionType\x18\x03 \x01(\x04R\x0fTransactionType\x12\x1c\n" +
	"\tCoinPrice\x18\x04 \x01(\x01R\tCoinPrice\x12\"\n" +
	"\fCoinQuantity\x18\x05 \x01(\x01R\fCoinQuantity\x12 \n" +
	"\vStablePrice\x18\x06 \x01(\x01R\vStablePrice\x12&\n" +
	"\x0eStableQuantity\x18\a \x01(\x01R\x0eStableQuantity\x120\n" +
	"\x13OperationExchangeId\x18\b \x01(\tR\x13OperationExchangeId\x128\n" +
	"\x17OperationExchangeStatus\x18\t \x01(\x04R\x17OperationExchangeStatus\x12\x10\n" +
	"\x03Fee\x18\n" +
	" \x01(\x01R\x03Fee\"X\n" +
	"\x1aGetOperationHistoryRequest\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x04R\aOrderId\x12 \n" +
	"\vOrderIdLink\x18\x02 \x01(\x04R\vOrderIdLink\"_\n" +
	"\x1bGetOperationHistoryResponse\x12@\n" +
	"\x10OperationHistory\x18\x01 \x01(\v2\x14.pb.OperationHistoryR\x10OperationHistory\"F\n" +
	"&ListOperationHistoryByOperationRequest\x12\x1c\n" +
	"\tOperation\x18\x01 \x01(\x04R\tOperation\"k\n" +
	"'ListOperationHistoryByOperationResponse\x12@\n" +
	"\x10OperationHistory\x18\x01 \x03(\v2\x14.pb.OperationHistoryR\x10OperationHistory\"D\n" +
	"$GetLastBuyRegisterByOperationRequest\x12\x1c\n" +
	"\tOperation\x18\x01 \x01(\x04R\tOperation\"u\n" +
	"%GetLastBuyRegisterByOperationResponse\x12\"\n" +
	"\fCoinQuantity\x18\x01 \x01(\x01R\fCoinQuantity\x12\x10\n" +
	"\x03Fee\x18\x02 \x01(\x01R\x03Fee\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\x04R\x06Status\"a\n" +
	"\x1dCreateOperationHistoryRequest\x12@\n" +
	"\x10OperationHistory\x18\x01 \x01(\v2\x14.pb.OperationHistoryR\x10OperationHistory\"b\n" +
	"\x1eCreateOperationHistoryResponse\x12@\n" +
	"\x10OperationHistory\x18\x01 \x01(\v2\x14.pb.OperationHistoryR\x10OperationHistory\"a\n" +
	"\x1dUpdateOperationHistoryRequest\x12@\n" +
	"\x10OperationHistory\x18\x01 \x01(\v2\x14.pb.OperationHistoryR\x10OperationHistory\"b\n" +
	"\x1eUpdateOperationHistoryResponse\x12@\n" +
	"\x10OperationHistory\x18\x01 \x01(\v2\x14.pb.OperationHistoryR\x10OperationHistoryB\x06Z\x04./pbb\x06proto3"

var (
	file_operation_history_proto_rawDescOnce sync.Once
	file_operation_history_proto_rawDescData []byte
)

func file_operation_history_proto_rawDescGZIP() []byte {
	file_operation_history_proto_rawDescOnce.Do(func() {
		file_operation_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_history_proto_rawDesc), len(file_operation_history_proto_rawDesc)))
	})
	return file_operation_history_proto_rawDescData
}

var file_operation_history_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_operation_history_proto_goTypes = []any{
	(*OperationHistory)(nil),                        // 0: pb.OperationHistory
	(*GetOperationHistoryRequest)(nil),              // 1: pb.GetOperationHistoryRequest
	(*GetOperationHistoryResponse)(nil),             // 2: pb.GetOperationHistoryResponse
	(*ListOperationHistoryByOperationRequest)(nil),  // 3: pb.ListOperationHistoryByOperationRequest
	(*ListOperationHistoryByOperationResponse)(nil), // 4: pb.ListOperationHistoryByOperationResponse
	(*GetLastBuyRegisterByOperationRequest)(nil),    // 5: pb.GetLastBuyRegisterByOperationRequest
	(*GetLastBuyRegisterByOperationResponse)(nil),   // 6: pb.GetLastBuyRegisterByOperationResponse
	(*CreateOperationHistoryRequest)(nil),           // 7: pb.CreateOperationHistoryRequest
	(*CreateOperationHistoryResponse)(nil),          // 8: pb.CreateOperationHistoryResponse
	(*UpdateOperationHistoryRequest)(nil),           // 9: pb.UpdateOperationHistoryRequest
	(*UpdateOperationHistoryResponse)(nil),          // 10: pb.UpdateOperationHistoryResponse
}
var file_operation_history_proto_depIdxs = []int32{
	0, // 0: pb.GetOperationHistoryResponse.OperationHistory:type_name -> pb.OperationHistory
	0, // 1: pb.ListOperationHistoryByOperationResponse.OperationHistory:type_name -> pb.OperationHistory
	0, // 2: pb.CreateOperationHistoryRequest.OperationHistory:type_name -> pb.OperationHistory
	0, // 3: pb.CreateOperationHistoryResponse.OperationHistory:type_name -> pb.OperationHistory
	0, // 4: pb.UpdateOperationHistoryRequest.OperationHistory:type_name -> pb.OperationHistory
	0, // 5: pb.UpdateOperationHistoryResponse.OperationHistory:type_name -> pb.OperationHistory
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_operation_history_proto_init() }
func file_operation_history_proto_init() {
	if File_operation_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_history_proto_rawDesc), len(file_operation_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operation_history_proto_goTypes,
		DependencyIndexes: file_operation_history_proto_depIdxs,
		MessageInfos:      file_operation_history_proto_msgTypes,
	}.Build()
	File_operation_history_proto = out.File
	file_operation_history_proto_goTypes = nil
	file_operation_history_proto_depIdxs = nil
}
