// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: operation_history.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLastBuyRegisterByOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     uint64                 `protobuf:"varint,1,opt,name=Operation,proto3" json:"Operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastBuyRegisterByOperationRequest) Reset() {
	*x = GetLastBuyRegisterByOperationRequest{}
	mi := &file_operation_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastBuyRegisterByOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastBuyRegisterByOperationRequest) ProtoMessage() {}

func (x *GetLastBuyRegisterByOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastBuyRegisterByOperationRequest.ProtoReflect.Descriptor instead.
func (*GetLastBuyRegisterByOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{0}
}

func (x *GetLastBuyRegisterByOperationRequest) GetOperation() uint64 {
	if x != nil {
		return x.Operation
	}
	return 0
}

type GetLastBuyRegisterByOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinQuantity  float64                `protobuf:"fixed64,1,opt,name=CoinQuantity,proto3" json:"CoinQuantity,omitempty"`
	Fee           float64                `protobuf:"fixed64,2,opt,name=Fee,proto3" json:"Fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastBuyRegisterByOperationResponse) Reset() {
	*x = GetLastBuyRegisterByOperationResponse{}
	mi := &file_operation_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastBuyRegisterByOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastBuyRegisterByOperationResponse) ProtoMessage() {}

func (x *GetLastBuyRegisterByOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastBuyRegisterByOperationResponse.ProtoReflect.Descriptor instead.
func (*GetLastBuyRegisterByOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetLastBuyRegisterByOperationResponse) GetCoinQuantity() float64 {
	if x != nil {
		return x.CoinQuantity
	}
	return 0
}

func (x *GetLastBuyRegisterByOperationResponse) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

var File_operation_history_proto protoreflect.FileDescriptor

var file_operation_history_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x44, 0x0a,
	0x24, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x75, 0x79, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x42, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x5d, 0x0a, 0x25, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x42, 0x75,
	0x79, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x42, 0x79, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x43, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x43, 0x6f, 0x69, 0x6e, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x46, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x46,
	0x65, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_operation_history_proto_rawDescOnce sync.Once
	file_operation_history_proto_rawDescData []byte
)

func file_operation_history_proto_rawDescGZIP() []byte {
	file_operation_history_proto_rawDescOnce.Do(func() {
		file_operation_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_history_proto_rawDesc), len(file_operation_history_proto_rawDesc)))
	})
	return file_operation_history_proto_rawDescData
}

var file_operation_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_operation_history_proto_goTypes = []any{
	(*GetLastBuyRegisterByOperationRequest)(nil),  // 0: pb.GetLastBuyRegisterByOperationRequest
	(*GetLastBuyRegisterByOperationResponse)(nil), // 1: pb.GetLastBuyRegisterByOperationResponse
}
var file_operation_history_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_operation_history_proto_init() }
func file_operation_history_proto_init() {
	if File_operation_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_history_proto_rawDesc), len(file_operation_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operation_history_proto_goTypes,
		DependencyIndexes: file_operation_history_proto_depIdxs,
		MessageInfos:      file_operation_history_proto_msgTypes,
	}.Build()
	File_operation_history_proto = out.File
	file_operation_history_proto_goTypes = nil
	file_operation_history_proto_depIdxs = nil
}
