// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: operation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Operation       uint64                 `protobuf:"varint,1,opt,name=operation,proto3" json:"operation,omitempty"`
	User            uint64                 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Parity          uint64                 `protobuf:"varint,3,opt,name=parity,proto3" json:"parity,omitempty"`
	Exchange        uint64                 `protobuf:"varint,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Strategy        uint64                 `protobuf:"varint,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	StrategyVariant uint64                 `protobuf:"varint,6,opt,name=strategy_variant,json=strategyVariant,proto3" json:"strategy_variant,omitempty"`
	MtsStart        uint64                 `protobuf:"varint,7,opt,name=mts_start,json=mtsStart,proto3" json:"mts_start,omitempty"`
	MtsFinish       uint64                 `protobuf:"varint,8,opt,name=mts_finish,json=mtsFinish,proto3" json:"mts_finish,omitempty"`
	OpenPrice       float64                `protobuf:"fixed64,9,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	ClosePrice      float64                `protobuf:"fixed64,10,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	InvestedAmount  float64                `protobuf:"fixed64,11,opt,name=invested_amount,json=investedAmount,proto3" json:"invested_amount,omitempty"`
	ProfitAmount    float64                `protobuf:"fixed64,12,opt,name=profit_amount,json=profitAmount,proto3" json:"profit_amount,omitempty"`
	Profit          float64                `protobuf:"fixed64,13,opt,name=profit,proto3" json:"profit,omitempty"`
	Closed          bool                   `protobuf:"varint,14,opt,name=closed,proto3" json:"closed,omitempty"`
	Audit           bool                   `protobuf:"varint,15,opt,name=audit,proto3" json:"audit,omitempty"`
	Enabled         bool                   `protobuf:"varint,16,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TimesCanceled   float64                `protobuf:"fixed64,17,opt,name=times_canceled,json=timesCanceled,proto3" json:"times_canceled,omitempty"`
	InTransaction   bool                   `protobuf:"varint,18,opt,name=in_transaction,json=inTransaction,proto3" json:"in_transaction,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetOperation() uint64 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *Operation) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *Operation) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *Operation) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

func (x *Operation) GetStrategy() uint64 {
	if x != nil {
		return x.Strategy
	}
	return 0
}

func (x *Operation) GetStrategyVariant() uint64 {
	if x != nil {
		return x.StrategyVariant
	}
	return 0
}

func (x *Operation) GetMtsStart() uint64 {
	if x != nil {
		return x.MtsStart
	}
	return 0
}

func (x *Operation) GetMtsFinish() uint64 {
	if x != nil {
		return x.MtsFinish
	}
	return 0
}

func (x *Operation) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *Operation) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *Operation) GetInvestedAmount() float64 {
	if x != nil {
		return x.InvestedAmount
	}
	return 0
}

func (x *Operation) GetProfitAmount() float64 {
	if x != nil {
		return x.ProfitAmount
	}
	return 0
}

func (x *Operation) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *Operation) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *Operation) GetAudit() bool {
	if x != nil {
		return x.Audit
	}
	return false
}

func (x *Operation) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Operation) GetTimesCanceled() float64 {
	if x != nil {
		return x.TimesCanceled
	}
	return 0
}

func (x *Operation) GetInTransaction() bool {
	if x != nil {
		return x.InTransaction
	}
	return false
}

type OperationJoin struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Operation           uint64                 `protobuf:"varint,1,opt,name=operation,proto3" json:"operation,omitempty"`
	User                uint64                 `protobuf:"varint,2,opt,name=user,proto3" json:"user,omitempty"`
	Parity              uint64                 `protobuf:"varint,3,opt,name=parity,proto3" json:"parity,omitempty"`
	Exchange            uint64                 `protobuf:"varint,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Strategy            uint64                 `protobuf:"varint,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	StrategyVariant     uint64                 `protobuf:"varint,6,opt,name=strategy_variant,json=strategyVariant,proto3" json:"strategy_variant,omitempty"`
	MtsStart            uint64                 `protobuf:"varint,7,opt,name=mts_start,json=mtsStart,proto3" json:"mts_start,omitempty"`
	MtsFinish           uint64                 `protobuf:"varint,8,opt,name=mts_finish,json=mtsFinish,proto3" json:"mts_finish,omitempty"`
	OpenPrice           float64                `protobuf:"fixed64,9,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	ClosePrice          float64                `protobuf:"fixed64,10,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	InvestedAmount      float64                `protobuf:"fixed64,11,opt,name=invested_amount,json=investedAmount,proto3" json:"invested_amount,omitempty"`
	ProfitAmount        float64                `protobuf:"fixed64,12,opt,name=profit_amount,json=profitAmount,proto3" json:"profit_amount,omitempty"`
	Profit              float64                `protobuf:"fixed64,13,opt,name=profit,proto3" json:"profit,omitempty"`
	Closed              bool                   `protobuf:"varint,14,opt,name=closed,proto3" json:"closed,omitempty"`
	Audit               bool                   `protobuf:"varint,15,opt,name=audit,proto3" json:"audit,omitempty"`
	Enabled             bool                   `protobuf:"varint,16,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TimesCanceled       float64                `protobuf:"fixed64,17,opt,name=times_canceled,json=timesCanceled,proto3" json:"times_canceled,omitempty"`
	ParitySymbol        string                 `protobuf:"bytes,18,opt,name=parity_symbol,json=paritySymbol,proto3" json:"parity_symbol,omitempty"`
	ExchangeName        string                 `protobuf:"bytes,19,opt,name=exchange_name,json=exchangeName,proto3" json:"exchange_name,omitempty"`
	StrategyName        string                 `protobuf:"bytes,20,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	StrategyVariantName string                 `protobuf:"bytes,21,opt,name=strategy_variant_name,json=strategyVariantName,proto3" json:"strategy_variant_name,omitempty"`
	InTransaction       bool                   `protobuf:"varint,22,opt,name=in_transaction,json=inTransaction,proto3" json:"in_transaction,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OperationJoin) Reset() {
	*x = OperationJoin{}
	mi := &file_operation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationJoin) ProtoMessage() {}

func (x *OperationJoin) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationJoin.ProtoReflect.Descriptor instead.
func (*OperationJoin) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{1}
}

func (x *OperationJoin) GetOperation() uint64 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *OperationJoin) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *OperationJoin) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *OperationJoin) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

func (x *OperationJoin) GetStrategy() uint64 {
	if x != nil {
		return x.Strategy
	}
	return 0
}

func (x *OperationJoin) GetStrategyVariant() uint64 {
	if x != nil {
		return x.StrategyVariant
	}
	return 0
}

func (x *OperationJoin) GetMtsStart() uint64 {
	if x != nil {
		return x.MtsStart
	}
	return 0
}

func (x *OperationJoin) GetMtsFinish() uint64 {
	if x != nil {
		return x.MtsFinish
	}
	return 0
}

func (x *OperationJoin) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *OperationJoin) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *OperationJoin) GetInvestedAmount() float64 {
	if x != nil {
		return x.InvestedAmount
	}
	return 0
}

func (x *OperationJoin) GetProfitAmount() float64 {
	if x != nil {
		return x.ProfitAmount
	}
	return 0
}

func (x *OperationJoin) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *OperationJoin) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *OperationJoin) GetAudit() bool {
	if x != nil {
		return x.Audit
	}
	return false
}

func (x *OperationJoin) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OperationJoin) GetTimesCanceled() float64 {
	if x != nil {
		return x.TimesCanceled
	}
	return 0
}

func (x *OperationJoin) GetParitySymbol() string {
	if x != nil {
		return x.ParitySymbol
	}
	return ""
}

func (x *OperationJoin) GetExchangeName() string {
	if x != nil {
		return x.ExchangeName
	}
	return ""
}

func (x *OperationJoin) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *OperationJoin) GetStrategyVariantName() string {
	if x != nil {
		return x.StrategyVariantName
	}
	return ""
}

func (x *OperationJoin) GetInTransaction() bool {
	if x != nil {
		return x.InTransaction
	}
	return false
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   uint64                 `protobuf:"varint,1,opt,name=operationId,proto3" json:"operationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_operation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationRequest) GetOperationId() uint64 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_operation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{3}
}

func (x *GetOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ListOperationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            uint64                 `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Strategy        uint64                 `protobuf:"varint,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	StrategyVariant uint64                 `protobuf:"varint,3,opt,name=strategy_variant,json=strategyVariant,proto3" json:"strategy_variant,omitempty"`
	Parity          uint64                 `protobuf:"varint,4,opt,name=parity,proto3" json:"parity,omitempty"`
	Exchange        uint64                 `protobuf:"varint,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Closed          bool                   `protobuf:"varint,6,opt,name=closed,proto3" json:"closed,omitempty"`
	Enabled         bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	InTransaction   bool                   `protobuf:"varint,8,opt,name=in_transaction,json=inTransaction,proto3" json:"in_transaction,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListOperationRequest) Reset() {
	*x = ListOperationRequest{}
	mi := &file_operation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationRequest) ProtoMessage() {}

func (x *ListOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationRequest.ProtoReflect.Descriptor instead.
func (*ListOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{4}
}

func (x *ListOperationRequest) GetUser() uint64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *ListOperationRequest) GetStrategy() uint64 {
	if x != nil {
		return x.Strategy
	}
	return 0
}

func (x *ListOperationRequest) GetStrategyVariant() uint64 {
	if x != nil {
		return x.StrategyVariant
	}
	return 0
}

func (x *ListOperationRequest) GetParity() uint64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *ListOperationRequest) GetExchange() uint64 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

func (x *ListOperationRequest) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *ListOperationRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ListOperationRequest) GetInTransaction() bool {
	if x != nil {
		return x.InTransaction
	}
	return false
}

type ListOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationResponse) Reset() {
	*x = ListOperationResponse{}
	mi := &file_operation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationResponse) ProtoMessage() {}

func (x *ListOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationResponse.ProtoReflect.Descriptor instead.
func (*ListOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{5}
}

func (x *ListOperationResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ListOperationByPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MtsStart      uint64                 `protobuf:"varint,1,opt,name=mts_start,json=mtsStart,proto3" json:"mts_start,omitempty"`
	MtsEnd        uint64                 `protobuf:"varint,2,opt,name=mts_end,json=mtsEnd,proto3" json:"mts_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationByPeriodRequest) Reset() {
	*x = ListOperationByPeriodRequest{}
	mi := &file_operation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationByPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationByPeriodRequest) ProtoMessage() {}

func (x *ListOperationByPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationByPeriodRequest.ProtoReflect.Descriptor instead.
func (*ListOperationByPeriodRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{6}
}

func (x *ListOperationByPeriodRequest) GetMtsStart() uint64 {
	if x != nil {
		return x.MtsStart
	}
	return 0
}

func (x *ListOperationByPeriodRequest) GetMtsEnd() uint64 {
	if x != nil {
		return x.MtsEnd
	}
	return 0
}

type ListOperationByPeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationByPeriodResponse) Reset() {
	*x = ListOperationByPeriodResponse{}
	mi := &file_operation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationByPeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationByPeriodResponse) ProtoMessage() {}

func (x *ListOperationByPeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationByPeriodResponse.ProtoReflect.Descriptor instead.
func (*ListOperationByPeriodResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{7}
}

func (x *ListOperationByPeriodResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ListOperationEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationEnabledRequest) Reset() {
	*x = ListOperationEnabledRequest{}
	mi := &file_operation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationEnabledRequest) ProtoMessage() {}

func (x *ListOperationEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationEnabledRequest.ProtoReflect.Descriptor instead.
func (*ListOperationEnabledRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{8}
}

type ListOperationEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*OperationJoin       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationEnabledResponse) Reset() {
	*x = ListOperationEnabledResponse{}
	mi := &file_operation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationEnabledResponse) ProtoMessage() {}

func (x *ListOperationEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationEnabledResponse.ProtoReflect.Descriptor instead.
func (*ListOperationEnabledResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{9}
}

func (x *ListOperationEnabledResponse) GetOperations() []*OperationJoin {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ListAllOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllOperationRequest) Reset() {
	*x = ListAllOperationRequest{}
	mi := &file_operation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllOperationRequest) ProtoMessage() {}

func (x *ListAllOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllOperationRequest.ProtoReflect.Descriptor instead.
func (*ListAllOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{10}
}

type ListAllOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*OperationJoin       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllOperationResponse) Reset() {
	*x = ListAllOperationResponse{}
	mi := &file_operation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllOperationResponse) ProtoMessage() {}

func (x *ListAllOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllOperationResponse.ProtoReflect.Descriptor instead.
func (*ListAllOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{11}
}

func (x *ListAllOperationResponse) GetOperations() []*OperationJoin {
	if x != nil {
		return x.Operations
	}
	return nil
}

type UpdateOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperationRequest) Reset() {
	*x = UpdateOperationRequest{}
	mi := &file_operation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperationRequest) ProtoMessage() {}

func (x *UpdateOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateOperationRequest) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type UpdateOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperationResponse) Reset() {
	*x = UpdateOperationResponse{}
	mi := &file_operation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperationResponse) ProtoMessage() {}

func (x *UpdateOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type CreateOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperationRequest) Reset() {
	*x = CreateOperationRequest{}
	mi := &file_operation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationRequest) ProtoMessage() {}

func (x *CreateOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationRequest.ProtoReflect.Descriptor instead.
func (*CreateOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{14}
}

func (x *CreateOperationRequest) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type CreateOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperationResponse) Reset() {
	*x = CreateOperationResponse{}
	mi := &file_operation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationResponse) ProtoMessage() {}

func (x *CreateOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationResponse.ProtoReflect.Descriptor instead.
func (*CreateOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_proto_rawDescGZIP(), []int{15}
}

func (x *CreateOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

var File_operation_proto protoreflect.FileDescriptor

const file_operation_proto_rawDesc = "" +
	"\n" +
	"\x0foperation.proto\x12\x02pb\"\xb0\x04\n" +
	"\tOperation\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\x04R\toperation\x12\x12\n" +
	"\x04user\x18\x02 \x01(\x04R\x04user\x12\x16\n" +
	"\x06parity\x18\x03 \x01(\x04R\x06parity\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\x04R\bexchange\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\x04R\bstrategy\x12)\n" +
	"\x10strategy_variant\x18\x06 \x01(\x04R\x0fstrategyVariant\x12\x1b\n" +
	"\tmts_start\x18\a \x01(\x04R\bmtsStart\x12\x1d\n" +
	"\n" +
	"mts_finish\x18\b \x01(\x04R\tmtsFinish\x12\x1d\n" +
	"\n" +
	"open_price\x18\t \x01(\x01R\topenPrice\x12\x1f\n" +
	"\vclose_price\x18\n" +
	" \x01(\x01R\n" +
	"closePrice\x12'\n" +
	"\x0finvested_amount\x18\v \x01(\x01R\x0einvestedAmount\x12#\n" +
	"\rprofit_amount\x18\f \x01(\x01R\fprofitAmount\x12\x16\n" +
	"\x06profit\x18\r \x01(\x01R\x06profit\x12\x16\n" +
	"\x06closed\x18\x0e \x01(\bR\x06closed\x12\x14\n" +
	"\x05audit\x18\x0f \x01(\bR\x05audit\x12\x18\n" +
	"\aenabled\x18\x10 \x01(\bR\aenabled\x12%\n" +
	"\x0etimes_canceled\x18\x11 \x01(\x01R\rtimesCanceled\x12%\n" +
	"\x0ein_transaction\x18\x12 \x01(\bR\rinTransaction\"\xd7\x05\n" +
	"\rOperationJoin\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\x04R\toperation\x12\x12\n" +
	"\x04user\x18\x02 \x01(\x04R\x04user\x12\x16\n" +
	"\x06parity\x18\x03 \x01(\x04R\x06parity\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\x04R\bexchange\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\x04R\bstrategy\x12)\n" +
	"\x10strategy_variant\x18\x06 \x01(\x04R\x0fstrategyVariant\x12\x1b\n" +
	"\tmts_start\x18\a \x01(\x04R\bmtsStart\x12\x1d\n" +
	"\n" +
	"mts_finish\x18\b \x01(\x04R\tmtsFinish\x12\x1d\n" +
	"\n" +
	"open_price\x18\t \x01(\x01R\topenPrice\x12\x1f\n" +
	"\vclose_price\x18\n" +
	" \x01(\x01R\n" +
	"closePrice\x12'\n" +
	"\x0finvested_amount\x18\v \x01(\x01R\x0einvestedAmount\x12#\n" +
	"\rprofit_amount\x18\f \x01(\x01R\fprofitAmount\x12\x16\n" +
	"\x06profit\x18\r \x01(\x01R\x06profit\x12\x16\n" +
	"\x06closed\x18\x0e \x01(\bR\x06closed\x12\x14\n" +
	"\x05audit\x18\x0f \x01(\bR\x05audit\x12\x18\n" +
	"\aenabled\x18\x10 \x01(\bR\aenabled\x12%\n" +
	"\x0etimes_canceled\x18\x11 \x01(\x01R\rtimesCanceled\x12#\n" +
	"\rparity_symbol\x18\x12 \x01(\tR\fparitySymbol\x12#\n" +
	"\rexchange_name\x18\x13 \x01(\tR\fexchangeName\x12#\n" +
	"\rstrategy_name\x18\x14 \x01(\tR\fstrategyName\x122\n" +
	"\x15strategy_variant_name\x18\x15 \x01(\tR\x13strategyVariantName\x12%\n" +
	"\x0ein_transaction\x18\x16 \x01(\bR\rinTransaction\"7\n" +
	"\x13GetOperationRequest\x12 \n" +
	"\voperationId\x18\x01 \x01(\x04R\voperationId\"C\n" +
	"\x14GetOperationResponse\x12+\n" +
	"\toperation\x18\x01 \x01(\v2\r.pb.OperationR\toperation\"\xfe\x01\n" +
	"\x14ListOperationRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\x04R\x04user\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\x04R\bstrategy\x12)\n" +
	"\x10strategy_variant\x18\x03 \x01(\x04R\x0fstrategyVariant\x12\x16\n" +
	"\x06parity\x18\x04 \x01(\x04R\x06parity\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\x04R\bexchange\x12\x16\n" +
	"\x06closed\x18\x06 \x01(\bR\x06closed\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12%\n" +
	"\x0ein_transaction\x18\b \x01(\bR\rinTransaction\"F\n" +
	"\x15ListOperationResponse\x12-\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\r.pb.OperationR\n" +
	"operations\"T\n" +
	"\x1cListOperationByPeriodRequest\x12\x1b\n" +
	"\tmts_start\x18\x01 \x01(\x04R\bmtsStart\x12\x17\n" +
	"\amts_end\x18\x02 \x01(\x04R\x06mtsEnd\"N\n" +
	"\x1dListOperationByPeriodResponse\x12-\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\r.pb.OperationR\n" +
	"operations\"\x1d\n" +
	"\x1bListOperationEnabledRequest\"Q\n" +
	"\x1cListOperationEnabledResponse\x121\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x11.pb.OperationJoinR\n" +
	"operations\"\x19\n" +
	"\x17ListAllOperationRequest\"M\n" +
	"\x18ListAllOperationResponse\x121\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x11.pb.OperationJoinR\n" +
	"operations\"E\n" +
	"\x16UpdateOperationRequest\x12+\n" +
	"\toperation\x18\x01 \x01(\v2\r.pb.OperationR\toperation\"F\n" +
	"\x17UpdateOperationResponse\x12+\n" +
	"\toperation\x18\x01 \x01(\v2\r.pb.OperationR\toperation\"E\n" +
	"\x16CreateOperationRequest\x12+\n" +
	"\toperation\x18\x01 \x01(\v2\r.pb.OperationR\toperation\"F\n" +
	"\x17CreateOperationResponse\x12+\n" +
	"\toperation\x18\x01 \x01(\v2\r.pb.OperationR\toperationB\x06Z\x04./pbb\x06proto3"

var (
	file_operation_proto_rawDescOnce sync.Once
	file_operation_proto_rawDescData []byte
)

func file_operation_proto_rawDescGZIP() []byte {
	file_operation_proto_rawDescOnce.Do(func() {
		file_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operation_proto_rawDesc), len(file_operation_proto_rawDesc)))
	})
	return file_operation_proto_rawDescData
}

var file_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_operation_proto_goTypes = []any{
	(*Operation)(nil),                     // 0: pb.Operation
	(*OperationJoin)(nil),                 // 1: pb.OperationJoin
	(*GetOperationRequest)(nil),           // 2: pb.GetOperationRequest
	(*GetOperationResponse)(nil),          // 3: pb.GetOperationResponse
	(*ListOperationRequest)(nil),          // 4: pb.ListOperationRequest
	(*ListOperationResponse)(nil),         // 5: pb.ListOperationResponse
	(*ListOperationByPeriodRequest)(nil),  // 6: pb.ListOperationByPeriodRequest
	(*ListOperationByPeriodResponse)(nil), // 7: pb.ListOperationByPeriodResponse
	(*ListOperationEnabledRequest)(nil),   // 8: pb.ListOperationEnabledRequest
	(*ListOperationEnabledResponse)(nil),  // 9: pb.ListOperationEnabledResponse
	(*ListAllOperationRequest)(nil),       // 10: pb.ListAllOperationRequest
	(*ListAllOperationResponse)(nil),      // 11: pb.ListAllOperationResponse
	(*UpdateOperationRequest)(nil),        // 12: pb.UpdateOperationRequest
	(*UpdateOperationResponse)(nil),       // 13: pb.UpdateOperationResponse
	(*CreateOperationRequest)(nil),        // 14: pb.CreateOperationRequest
	(*CreateOperationResponse)(nil),       // 15: pb.CreateOperationResponse
}
var file_operation_proto_depIdxs = []int32{
	0, // 0: pb.GetOperationResponse.operation:type_name -> pb.Operation
	0, // 1: pb.ListOperationResponse.operations:type_name -> pb.Operation
	0, // 2: pb.ListOperationByPeriodResponse.operations:type_name -> pb.Operation
	1, // 3: pb.ListOperationEnabledResponse.operations:type_name -> pb.OperationJoin
	1, // 4: pb.ListAllOperationResponse.operations:type_name -> pb.OperationJoin
	0, // 5: pb.UpdateOperationRequest.operation:type_name -> pb.Operation
	0, // 6: pb.UpdateOperationResponse.operation:type_name -> pb.Operation
	0, // 7: pb.CreateOperationRequest.operation:type_name -> pb.Operation
	0, // 8: pb.CreateOperationResponse.operation:type_name -> pb.Operation
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_operation_proto_init() }
func file_operation_proto_init() {
	if File_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operation_proto_rawDesc), len(file_operation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_operation_proto_goTypes,
		DependencyIndexes: file_operation_proto_depIdxs,
		MessageInfos:      file_operation_proto_msgTypes,
	}.Build()
	File_operation_proto = out.File
	file_operation_proto_goTypes = nil
	file_operation_proto_depIdxs = nil
}
