// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: trade_config.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradeConfigService_ListTradeConfig_FullMethodName   = "/pb.TradeConfigService/ListTradeConfig"
	TradeConfigService_CreateTradeConfig_FullMethodName = "/pb.TradeConfigService/CreateTradeConfig"
)

// TradeConfigServiceClient is the client API for TradeConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeConfigServiceClient interface {
	ListTradeConfig(ctx context.Context, in *ListTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error)
	CreateTradeConfig(ctx context.Context, in *CreateTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error)
}

type tradeConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeConfigServiceClient(cc grpc.ClientConnInterface) TradeConfigServiceClient {
	return &tradeConfigServiceClient{cc}
}

func (c *tradeConfigServiceClient) ListTradeConfig(ctx context.Context, in *ListTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeConfigResponse)
	err := c.cc.Invoke(ctx, TradeConfigService_ListTradeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeConfigServiceClient) CreateTradeConfig(ctx context.Context, in *CreateTradeConfigRequest, opts ...grpc.CallOption) (*TradeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TradeConfigResponse)
	err := c.cc.Invoke(ctx, TradeConfigService_CreateTradeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeConfigServiceServer is the server API for TradeConfigService service.
// All implementations must embed UnimplementedTradeConfigServiceServer
// for forward compatibility.
type TradeConfigServiceServer interface {
	ListTradeConfig(context.Context, *ListTradeConfigRequest) (*TradeConfigResponse, error)
	CreateTradeConfig(context.Context, *CreateTradeConfigRequest) (*TradeConfigResponse, error)
	mustEmbedUnimplementedTradeConfigServiceServer()
}

// UnimplementedTradeConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradeConfigServiceServer struct{}

func (UnimplementedTradeConfigServiceServer) ListTradeConfig(context.Context, *ListTradeConfigRequest) (*TradeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTradeConfig not implemented")
}
func (UnimplementedTradeConfigServiceServer) CreateTradeConfig(context.Context, *CreateTradeConfigRequest) (*TradeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTradeConfig not implemented")
}
func (UnimplementedTradeConfigServiceServer) mustEmbedUnimplementedTradeConfigServiceServer() {}
func (UnimplementedTradeConfigServiceServer) testEmbeddedByValue()                            {}

// UnsafeTradeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeConfigServiceServer will
// result in compilation errors.
type UnsafeTradeConfigServiceServer interface {
	mustEmbedUnimplementedTradeConfigServiceServer()
}

func RegisterTradeConfigServiceServer(s grpc.ServiceRegistrar, srv TradeConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedTradeConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradeConfigService_ServiceDesc, srv)
}

func _TradeConfigService_ListTradeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeConfigServiceServer).ListTradeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeConfigService_ListTradeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeConfigServiceServer).ListTradeConfig(ctx, req.(*ListTradeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradeConfigService_CreateTradeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeConfigServiceServer).CreateTradeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradeConfigService_CreateTradeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeConfigServiceServer).CreateTradeConfig(ctx, req.(*CreateTradeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradeConfigService_ServiceDesc is the grpc.ServiceDesc for TradeConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradeConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TradeConfigService",
	HandlerType: (*TradeConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTradeConfig",
			Handler:    _TradeConfigService_ListTradeConfig_Handler,
		},
		{
			MethodName: "CreateTradeConfig",
			Handler:    _TradeConfigService_CreateTradeConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trade_config.proto",
}
