// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: transaction_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionType uint64                 `protobuf:"varint,1,opt,name=TransactionType,proto3" json:"TransactionType,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Active          bool                   `protobuf:"varint,3,opt,name=Active,proto3" json:"Active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionType) Reset() {
	*x = TransactionType{}
	mi := &file_transaction_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionType) ProtoMessage() {}

func (x *TransactionType) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionType.ProtoReflect.Descriptor instead.
func (*TransactionType) Descriptor() ([]byte, []int) {
	return file_transaction_type_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionType) GetTransactionType() uint64 {
	if x != nil {
		return x.TransactionType
	}
	return 0
}

func (x *TransactionType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionType) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type ListTransactionTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionTypeRequest) Reset() {
	*x = ListTransactionTypeRequest{}
	mi := &file_transaction_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionTypeRequest) ProtoMessage() {}

func (x *ListTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_transaction_type_proto_rawDescGZIP(), []int{1}
}

type ListTransactionTypeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionTypes []*TransactionType     `protobuf:"bytes,1,rep,name=TransactionTypes,proto3" json:"TransactionTypes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTransactionTypeResponse) Reset() {
	*x = ListTransactionTypeResponse{}
	mi := &file_transaction_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionTypeResponse) ProtoMessage() {}

func (x *ListTransactionTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionTypeResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionTypeResponse) Descriptor() ([]byte, []int) {
	return file_transaction_type_proto_rawDescGZIP(), []int{2}
}

func (x *ListTransactionTypeResponse) GetTransactionTypes() []*TransactionType {
	if x != nil {
		return x.TransactionTypes
	}
	return nil
}

var File_transaction_type_proto protoreflect.FileDescriptor

const file_transaction_type_proto_rawDesc = "" +
	"\n" +
	"\x16transaction_type.proto\x12\x02pb\"u\n" +
	"\x0fTransactionType\x12(\n" +
	"\x0fTransactionType\x18\x01 \x01(\x04R\x0fTransactionType\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12\x16\n" +
	"\x06Active\x18\x03 \x01(\bR\x06Active\"\x1c\n" +
	"\x1aListTransactionTypeRequest\"^\n" +
	"\x1bListTransactionTypeResponse\x12?\n" +
	"\x10TransactionTypes\x18\x01 \x03(\v2\x13.pb.TransactionTypeR\x10TransactionTypesB\x06Z\x04./pbb\x06proto3"

var (
	file_transaction_type_proto_rawDescOnce sync.Once
	file_transaction_type_proto_rawDescData []byte
)

func file_transaction_type_proto_rawDescGZIP() []byte {
	file_transaction_type_proto_rawDescOnce.Do(func() {
		file_transaction_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_type_proto_rawDesc), len(file_transaction_type_proto_rawDesc)))
	})
	return file_transaction_type_proto_rawDescData
}

var file_transaction_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transaction_type_proto_goTypes = []any{
	(*TransactionType)(nil),             // 0: pb.TransactionType
	(*ListTransactionTypeRequest)(nil),  // 1: pb.ListTransactionTypeRequest
	(*ListTransactionTypeResponse)(nil), // 2: pb.ListTransactionTypeResponse
}
var file_transaction_type_proto_depIdxs = []int32{
	0, // 0: pb.ListTransactionTypeResponse.TransactionTypes:type_name -> pb.TransactionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_type_proto_init() }
func file_transaction_type_proto_init() {
	if File_transaction_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_type_proto_rawDesc), len(file_transaction_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_type_proto_goTypes,
		DependencyIndexes: file_transaction_type_proto_depIdxs,
		MessageInfos:      file_transaction_type_proto_msgTypes,
	}.Build()
	File_transaction_type_proto = out.File
	file_transaction_type_proto_goTypes = nil
	file_transaction_type_proto_depIdxs = nil
}
